### PR TITLE
Task list HTML and CSS Structure

### LINKED ISSUE #2: Task List
Create the Task List Page with HTML and CSS and Page Navigation

### PR DESCRIPTION
**Pull request by KaustubhPaliwal**
It has the completed HTML and CSS file structure, with an initial implementation of JavaScript, also links to other completed HTML Pages.

Closes #2

### CODE REVIEW

**Comment by KaustubhPaliwal** [comment]
Fixed the suggestions and unified design and standardized file names

**Review by kevku — APPROVED** [review]
Completed the Task List and implementation. Fixed any issues with main branch.

**Review by erhuang623 — APPROVED** [review]
Seems good, changed semantic for buttons on index.html and added style, script, and basis for task list.

**Comment by KaustubhPaliwal** [comment]
Merged after review

**Pull request merged**
