### PR TITLE
Updated static.yml

### PR DESCRIPTION
**Pull request by jochshen**
Fixed path issue - *not yet*

- need to fix deployed path from `static.yml`. The current path is not working.

### CODE REVIEW

**Review by ulises0516 — APPROVED** [review]
Changes back to a "semi" fixed deployment. It deploys however, the link does not direct you to the dashboard. Will work on this later for now we using this solution but going to address soon.

**Review by b1luu — COMMENTED** [review]
Partial solution to static.yml pathway. More specifically, the path leads to a different link than expected, a bug that will be fixed in the future.

**Comment by b1luu** [comment]
Agreed and its for the benefit of current pushes so we don't disrupt work flow.

**Review by b1luu — APPROVED** [review]
Looks good and I agree that this way could create errors so reverting to old path that partially works is suited.

**Pull request merged**
