### PR TITLE
Event parse code update

### LINKED ISSUE #122: Parse out events in the Recent updates in the Dashboard

### LINKED ISSUE #125: Fix the scrolling on the dashboard for mobile view

### PR DESCRIPTION
**Pull request by kevku**
## Pull Request

**Description**
A clear and concise description of what this pull request is about.

**Type of change**
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Checklist**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

**Related Issues**
Fixes #125 
Fixes #122 
Fixes the + on code log on mobile view

**Screenshots**
sidebar
events
codelog

### CODE REVIEW

**Review by erhuang623 — DISMISSED** [review]
This fix will make our responsiveness better! The mobile view on the phone is sort of jankey. Will focus on more responsiveness

**Comment by SamvathnaEm** [comment]
This new implementation enhances the ability to edit tasks without a specified date, add or edit events without a specified time, and automatically sort tasks in local storage. Importantly, the dashboard now accurately reflects all tasks and events added by users, which is crucial for cross-feature integration. I really appreciate this new updates.

**Review by ulises0516 — APPROVED** [review]
I reviewed the changes and I am very please with the changes you guys made! The enhanced responsiveness will ensure a better user experience. I also really like the task management improvements. Also what a great idea to automatically sort tasks in local storage. This will ensure tasks are organized efficiently. The cross feature for the dashboard, now being displayed correctly is great. I appreciate all the changes made.

**Review by SamvathnaEm — APPROVED** [review]
This new implementation enhances the ability to edit tasks without a specified date, add or edit events without a specified time, and automatically sort tasks in local storage. Importantly, the dashboard now accurately reflects all tasks and events added by users, which is crucial for cross-feature integration. I really appreciate these updates.

**Review by erhuang623 — APPROVED** [review]
Nice work. Thanks for fixing the functionality of the dashboard updates and part of the calendar. These bug fixes are great.

**Pull request merged**
