### PR TITLE
Updated SideBar and Title Bar

### LINKED ISSUE #3: Team Calendar
Create the Team Calendar with HTML and CSS, and implement Page Navigation features

### LINKED ISSUE #5: Documentation
Implement Documentation in HTML and CSS with Page Navigation Features

### LINKED ISSUE #6: Feedback
Implement Feedback in HTML and CSS with Page Navigation Features

### LINKED ISSUE #10: Create a mobile view for the dashboard screen

### LINKED ISSUE #12: Fix Icon Sizes for Responsive Purposes
When resizing the window, the icons have weird sizes.

### LINKED ISSUE #16: Make the sidebar actually link to the individual pages
Change <button> tags in sidebar to <a> tags. 

Recheck styling

### LINKED ISSUE #17: Create individual pages for each of the features with just the sidebar and title

### LINKED ISSUE #19: Design the Team Calendar matching the colors of the mockup design
use css to customize the team calendar page

### LINKED ISSUE #32: Feedback CSS for Phone
Add CSS in feedback.css for better functionality with all screen sizes

### PR DESCRIPTION
**Pull request by KaustubhPaliwal**
Updated SideBar and Title Bar for all pages and adapted the css to work with mobile view

Closes #32, closes #10, closes #17, closes #19, closes #16, closes #12, closes #6, closes #5, closes #3;

### CODE REVIEW

**Review by kevku — APPROVED** [review]
Changed file location for organization, added sidebar for all pages including the mobile view

**Review by jochshen — APPROVED** [review]
Great, glad we were able to better organize the files into their respective folders.

**Review by nicholas-ngyn — DISMISSED** [review]
all the sidebar and title bar looks good!

**Review by cheung-arthur — APPROVED** [review]
Looks good to me

**Review by ulises0516 — DISMISSED** [review]
Beautiful work love the changes !

**Review by cheung-arthur — DISMISSED** [review]
Looks good to me

**Review by kevku — DISMISSED** [review]
Looks good

**Review by jochshen — DISMISSED** [review]
Looks good, hope the pr works.

**Review by kevku — APPROVED** [review]
Looks good

**Review by jochshen — APPROVED** [review]
Looks good, should be able to pr now

**Pull request merged**
