### PR TITLE
added delete button to Documentation page

### LINKED ISSUE #56: Add delete button on the Documentation page
Add in a button that would later allow the user to delete the current document that they are on.

### PR DESCRIPTION
**Pull request by nicholas-ngyn**
Added a delete button to Documentation page and styled it.

Closes #56

### CODE REVIEW

**Review by KaustubhPaliwal — DISMISSED** [review]
Looks good, can you change the color to out Purple for now (before we add the new theme) and the text inside to the Laker Gold, Thanks!

**Review by kevku — DISMISSED** [review]
Styled for documentation page and added delete option

**Review by jochshen — CHANGES_REQUESTED** [review]
I noticed that there's camelCase and kebab-case. `id="documentationHolder"` vs `id="textarea-wrapper"`. I'll ask what convention we should stick with.

**Review by erhuang623 — DISMISSED** [review]
Good work! This is vital for this feature!

**Review by ulises0516 — DISMISSED** [review]
I like the new feature! It looks more clean than the old delete and overall better for the user. Great job !

**Review by jochshen — APPROVED** [review]
Thanks for changing the styling, making it consistent so that ids are camelCase and classes are kebab-case

**Review by erhuang623 — APPROVED** [review]
Good work! this fixes the functionality of this feature!

**Review by kevku — APPROVED** [review]
Fixed naming conventions and added the delete button along with CSS changes

**Pull request merged**
