### PR TITLE
Sidebar changes merge main

### PR DESCRIPTION
**Pull request by kevku**
1. There was reformatting of the site because Jash wanted the header to be equal size with the logo so the header was moved outside and the navbar is going to be dynamically allocated by JavaScript for developing purposes. When we finalize the project and be completely done with the navbar, we can add the semantic elements into each page.
2. During the Merging process some files did not show up in main. For example, the documentation team's css, html was not updated, so double check if any of your files/edits are missing since your commit/push.
3. We will need to be more careful about how we merge our new content (We will probably announce to everyone when a merge happens to main, and those who are still working on their own branch will need to pull the new updates).
4. In the dashboard.css, I added a quick view of the dashboard when it's for mobile.
5. Please merge when everyone has reviewed the changes

### CODE REVIEW

**Review by ulises0516 — APPROVED** [review]
Great work! We finished the deployment part of the workflow so maybe we can add it before doing this pr. So we can roll back and they won’t dock us points for not using the workflow a little more. Please message josh if you want to do this though to copy and paste it over since I won’t be available most of the day tomorrow until the meeting m.

**Review by erhuang623 — APPROVED** [review]
Looks good! Implementing the idea of having the sidebar be imported is pretty practical for using it in multiple pages. We do need to be careful as importing that part might com with some styling that affects other pages.

**Review by KaustubhPaliwal — APPROVED** [review]
Looks good, I can reformat all the pages according to the updated modular architecture, and then open a new pr

**Review by nicholas-ngyn — APPROVED** [review]
Everything looks great for the Documentation page and the mobile view of it.

**Pull request merged**
