### PR TITLE
Refactor

### LINKED ISSUE #156: Refactor
## Task

**What is the task?**
Refactor some code based on linting suggestions

**Why is this task important?**
This makes our code more readable
**What steps are needed to complete the task?**
1. Run lint
2. read suggestions 
3.  make changes accordingly

### PR DESCRIPTION
**Pull request by nicholas-ngyn**
## Pull Request

**Description**
A clear and concise description of what this pull request is about.
Delete all unneeded functions (refactor)
Reformatted every JS files comments
Changed file names to be similar

**Type of change**
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Checklist**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

**Related Issues**
Please link the issue this pull request addresses. If applicable, add 'Fixes #<issue number>'.
Fixes #156 

**Screenshots**
If applicable, add screenshots to help explain your changes.

**Additional context**
Add any other context or screenshots about the pull request here.
N/A

### CODE REVIEW

**Review by jochshen — DISMISSED** [review]
thank you for refactoring the code in terms of the files naming conventions because it wasn't consistent. I also saw that you refactored other stuff and small fixes as well. Hope it doesn't break :p

**Review by cheung-arthur — APPROVED** [review]
LGTM

**Comment by jochshen** [comment]
seems like the code broke which is quite unlucky, but im glad we were able to fix it

**Comment by jochshen** [comment]
good work joshua

**Comment by jochshen** [comment]
thanks I know

**Comment by jochshen** [comment]
let's not let that happen again

**Review by jochshen — APPROVED** [review]
LGTM

**Review by erhuang623 — APPROVED** [review]
Thanks for refactoring all the files and fixing test conflicts! This ensures quality and stops "code smell."

**Review by kevku — APPROVED** [review]
Thank you for making everything consistent and the hard work of refactoring everything. :)

**Pull request merged**
